# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PhotoGalleryRN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoGalleryRN
  pod 'Vapor', '~> 4.0'

  target 'PhotoGalleryRNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end